site_name: 'prueba-docs'
repo_url: https://github.com/ucbg6/prueba-docs/
docs_dir: '.'

nav:
 - Pagina principal: README.md
 - Backstage: docs/index.md
 - Otra pagina: docs/page2.md

plugins:
 - techdocs-core
 - same-dir
 - plantuml:
        puml_url: https://www.plantuml.com/plantuml/
        num_workers: 4
